name: CI

on:
  pull_request:
    branches: ["*"]
  push:
    branches: ["main"]

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true


jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Cache
      uses: coursier/cache-action@v6

    - name: Setup Java
      uses: actions/setup-java@v2
      with:
          distribution: adopt
          java-version: 11

    - name: Run tests
      run: |
        ./mill -k --disable-ticker __.resolvedIvyDeps &&
        ./mill -k --disable-ticker mill.scalalib.scalafmt.ScalafmtModule/checkFormatAll __.sources &&
        ./mill -j 0 -k --disable-ticker __.test
